CREATE TABLE IF NOT EXISTS grants(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  application_id VARCHAR(20) NOT NULL,
  start_at DATE,
  grant_type VARCHAR(10),
  total_cost INTEGER
);

CREATE TABLE IF NOT EXISTS articles(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  PMID VARCHAR(20) NOT NULL,
  PubDate DATE
);

CREATE TABLE IF NOT EXISTS bridge(
  application_id INTEGER NOT NULL,
  PMID INTEGER NOT NULL
  
);