from dtsc330_26.misspelling_problem import seq2seq_transformer

if __name__ == "__main__":
    # Training data
    # I'm not as comfortable with the programming of the model,
    # so I referenced the code from Dr. Sugden's GitHub and 
    # got a solid understanding of how everything functions.
    # I am more comfortable with creating training data, 
    # so that is what I focused more on for this assignment.

    pairs = [
    ("accomodate", "accommodate"),
    ("acomodate", "accommodate"),
    ("acheive", "achieve"),
    ("acknowlege", "acknowledge"),
    ("arguement", "argument"),
    ("beleive", "believe"),
    ("begining", "beginning"),
    ("belive", "believe"),
    ("buisness", "business"),
    ("cemetary", "cemetery"),
    ("calender", "calendar"),
    ("camoflage", "camouflage"),
    ("occurence", "occurrence"),
    ("occuring", "occurring"),
    ("definately", "definitely"),
    ("dilemna", "dilemma"),
    ("dillema", "dilemma"),
    ("embarass", "embarrass"),
    ("enviroment", "environment"),
    ("existance", "existence"),
    ("exhilerate", "exhilarate"),
    ("expresso", "espresso"),
    ("febuary", "february"),
    ("foriegn", "foreign"),
    ("fourty", "forty"),
    ("gaurd", "guard"),
    ("goverment", "government"),
    ("gravely", "grievously"),
    ("greatful", "grateful"),
    ("harrass", "harass"),
    ("heigth", "height"),
    ("humerous", "humorous"),
    ("ignoring", "ignoring"),
    ("imediately", "immediately"),
    ("independant", "independent"),
    ("indispensible", "indispensable"),
    ("initally", "initially"),
    ("innocent", "innocent"),
    ("inteligent", "intelligent"),
    ("jewellry", "jewelry"),
    ("judgement", "judgment"),
    ("knowlege", "knowledge"),
    ("labratory", "laboratory"),
    ("liason", "liaison"),
    ("libary", "library"),
    ("maintainance", "maintenance"),
    ("mangement", "management"),
    ("medeval", "medieval"),
    ("millenium", "millennium"),
    ("miniture", "miniature"),
    ("neccessary", "necessary"),
    ("negociate", "negotiate"),
    ("occurence", "occurrence"),
    ("parliment", "parliament"),
    ("posession", "possession"),
    ("publically", "publicly"),
    ("recieve", "receive"),
    ("recommend", "recommend"),
    ("refered", "referred"),
    ("religous", "religious"),
    ("remeber", "remember"),
    ("resistence", "resistance"),
    ("seperate", "separate"),
    ("sieze", "seize"),
    ("supercede", "supersede"),
    ("tatoo", "tattoo"),
    ("teh", "the"),
    ("thier", "their"),
    ("tommorow", "tomorrow"),
    ("tounge", "tongue"),
    ("truely", "truly"),
    ("unecessary", "unnecessary"),
    ("until", "until"),
    ("wierd", "weird"),
    ("writting", "writing"),
    ("acquaintence", "acquaintance"),
    ("adress", "address"),
    ("advice", "advice"),
    ("apparant", "apparent"),
    ("arguably", "arguably"),
    ("athelete", "athlete"),
    ("bisquit", "biscuit"),
    ("cacheing", "caching"),
    ("carreer", "career"),
    ("cemetary", "cemetery"),
    ("collage", "college"),
    ("comming", "coming"),
    ("comparitive", "comparative"),
    ("congradulate", "congratulate"),
    ("conscience", "conscience"),
    ("definate", "definite"),
    ("dependant", "dependent"),
    ("dissapear", "disappear"),
    ("dissapoint", "disappoint"),
    ("embarased", "embarrassed"),
    ("experiance", "experience"),
    ("fluorescent", "fluorescent"),
    ("foriegn", "foreign"),
    ("frige", "fridge"),
    ("gauge", "gauge"),
    ("guage", "gauge"),
    ("hieght", "height"),
    ("humour", "humor"),
    ("humerous", "humorous"),
    ("incidence", "incidence"),
    ("indespensible", "indispensable"),
    ("interupt", "interrupt"),
    ("irrelevent", "irrelevant"),
    ("knowlege", "knowledge"),
    ("liquify", "liquefy"),
    ("maintenence", "maintenance"),
    ("mischevious", "mischievous"),
    ("milege", "mileage"),
    ("mispell", "misspell"),
    ("neccessary", "necessary"),
    ("ocassion", "occasion"),
    ("occurance", "occurrence"),
    ("pavillion", "pavilion"),
    ("perseverence", "perseverance"),
    ("pharoah", "pharaoh"),
    ("presance", "presence"),
    ("priviledge", "privilege"),
    ("pronunciation", "pronunciation"),
    ("reccommend", "recommend"),
    ("referance", "reference"),
    ("rythm", "rhythm"),
    ("sargant", "sergeant"),
    ("sieze", "seize"),
    ("somehow", "somehow"),
    ("treshold", "threshold"),
    ("truely", "truly"),
    ("tyrany", "tyranny"),
    ("undefinable", "undefinable"),
    ("viciously", "viciously"),
    ("wensday", "wednesday"),
    ("wich", "which"),
    ("yatch", "yacht"),
    ("freind", "friend"),
    ("darknes", "darkness"),
    ("calender", "calendar")
    ]

    s2s = seq2seq_transformer.Seq2SeqTransformer()
    s2s.fit(pairs)

    print(s2s.correct('tyranical')) # printed "tyranncal" (really close...swapped i for n instead of added another n)
    print(s2s.correct('freindship')) # printed "friendashi" (kinda knows how to do i-e and e-i swaps, also 'friend' is in the training set))
    print(s2s.correct('nieghbor')) # printed "neighbor" (got it!!!)
    print(s2s.correct('rhythim')) # printed "rhthtim" (not really close)
    print(s2s.correct("rythm")) # printed "rhythm" (it's in the training set, so it better have gotten this one)

    # trying on some words that are already correctly spelled

    print(s2s.correct('horrible')) # printed "horeible" (I have lots of e-i swaps in my traning set, so this makes sense)
    print(s2s.correct('system')) # printed "systemm" (added an m to the end)
    print(s2s.correct('volunteer')) # printed "volunterer" (inserted an extra r)